import { ReservationProvider } from "@/src/components/ReservationContext";
import "../src/_styles/global.css";
import { Josefin_Sans } from "next/font/google";
import Header from "@/src/components/Header";
const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "The wild osasis",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${josefin.className} relative antialiased bg-primary-950 text-primary-100 min-h-screen flex flex-col`}>
        <Header />
        <div className="flex-1 px-8 grid">
          <main className="mx-auto max-w-7xl w-full ">
            <ReservationProvider>{children}</ReservationProvider>
          </main>
        </div>
      </body>
    </html>
  );
}
